# 01 - Basic Tensor Operations in PyTorch

This notebook introduces basic tensor operations in PyTorch, including tensor creation, indexing, slicing, and reshaping. Understanding these operations is fundamental to utilizing PyTorch effectively in deep learning tasks.

## 1. Creating Tensors

Tensors are the core data structure in PyTorch, similar to NumPy arrays but with additional capabilities for automatic differentiation and GPU acceleration. There are several ways to create tensors in PyTorch:
- **Directly from data**: Using `torch.tensor()`.
- **From NumPy arrays**: Using `torch.from_numpy()`.
- **Using built-in functions**: Such as `torch.zeros()`, `torch.ones()`, `torch.arange()`, etc.


In [24]:
# Example: Creating Tensors
import torch

# Directly from data
tensor_from_data = torch.tensor([[1, 2, 3], [4, 5, 6]])
print('Tensor from data:', tensor_from_data)

# From NumPy array
import numpy as np
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print('Tensor from NumPy array:', tensor_from_numpy)

# Using built-in functions
zeros_tensor = torch.zeros((2, 3))
print('Zeros Tensor:', zeros_tensor)
ones_tensor = torch.ones((2, 3))
print('Ones Tensor:', ones_tensor)
arange_tensor = torch.arange(0, 10, 2)
print('Arange Tensor:', arange_tensor)

Tensor from data: tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor from NumPy array: tensor([1, 2, 3])
Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Arange Tensor: tensor([0, 2, 4, 6, 8])


## 2. Indexing Tensors

Indexing in PyTorch is similar to indexing in NumPy. It allows accessing specific elements, rows, columns, or slices of tensors. Indexing starts from 0, and negative indexing is supported as well.


In [25]:
# Example: Indexing Tensors
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Original Tensor:\n', tensor)

# Indexing a single element
element = tensor[0, 1]
print('Element at row 0, column 1:', element)

# Indexing a single row
row = tensor[1]
print('Row at index 1:', row)

# Indexing with negative indices
last_element = tensor[-1, -1]
print('Last element of the tensor:', last_element)

Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element at row 0, column 1: tensor(2)
Row at index 1: tensor([4, 5, 6])
Last element of the tensor: tensor(9)


## 3. Slicing Tensors

Slicing is used to access a range of elements in tensors. It allows selection of sub-tensors using a start, stop, and step, similar to Python lists or NumPy arrays.


In [26]:
# Example: Slicing Tensors
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a range of rows and columns
slice_1 = tensor[:2, 1:]
print('Slice of first two rows and last two columns:\n', slice_1)

# Slicing with a step
slice_2 = tensor[::2, ::2]
print('Slice with step 2:\n', slice_2)

Slice of first two rows and last two columns:
 tensor([[2, 3],
        [5, 6]])
Slice with step 2:
 tensor([[1, 3],
        [7, 9]])


## 4. Reshaping Tensors

Reshaping changes the shape of a tensor without altering its data. PyTorch provides the `reshape()` function for this purpose, as well as `view()` for contiguous tensors.


In [27]:
# Example: Reshaping Tensors
tensor = torch.arange(1, 10)
print('Original Tensor:', tensor)

# Reshape to a 3x3 matrix
reshaped_tensor = tensor.reshape(3, 3)
print('Reshaped Tensor (3x3):\n', reshaped_tensor)

# Using view() to reshape
view_tensor = tensor.view(3, 3)
print('View Tensor (3x3):\n', view_tensor)

Original Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped Tensor (3x3):
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
View Tensor (3x3):
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Exercises

1. Create a tensor of shape (4, 5) with random integers and print it.
2. Extract the second row and third column from the tensor created above.
3. Slice the tensor to get a 2x3 sub-tensor and print it.
4. Reshape the original tensor into a shape of (2, 10) and (10, 2) and print both.

In [28]:
tensor = torch.randint(low=0, high=100, size=(4,5))
tensor

tensor([[42, 14, 59, 63, 73],
        [64, 67, 15, 29,  7],
        [98, 99, 56, 95, 85],
        [76, 28, 79, 64, 12]])

In [29]:
tensor[1, 2]

tensor(15)

In [30]:
tensor[:2, :3]

tensor([[42, 14, 59],
        [64, 67, 15]])

In [31]:
tensor.reshape(shape=(2, 10))

tensor([[42, 14, 59, 63, 73, 64, 67, 15, 29,  7],
        [98, 99, 56, 95, 85, 76, 28, 79, 64, 12]])

In [32]:
tensor.reshape(shape=(10, 2))

tensor([[42, 14],
        [59, 63],
        [73, 64],
        [67, 15],
        [29,  7],
        [98, 99],
        [56, 95],
        [85, 76],
        [28, 79],
        [64, 12]])