In [1]:
# Import the necessary libraries for the task.
import numpy as np  # Import NumPy for numerical operations.
import torch  # Import PyTorch library for deep learning.
import torch.nn as nn  # Import neural network module from PyTorch.


In [2]:
# Define two neural network models: 'custom_widenet' and 'custom_deepnet'.
custom_widenet = nn.Sequential(
    nn.Linear(2, 4),  # Hidden layer with 2 input features and 4 output units.
    nn.Linear(4, 3),  # Output layer with 4 input units and 3 output units.
)

custom_deepnet = nn.Sequential(
    nn.Linear(2, 2),  # First hidden layer with 2 input features and 2 output units.
    nn.Linear(2, 2),  # Second hidden layer with 2 input units and 2 output units.
    nn.Linear(2, 3),  # Output layer with 2 input units and 3 output units.
)

# Print the model architectures for inspection.
print(custom_widenet)
print(' ')
print(custom_deepnet)


Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [5]:
# Explore the attributes of 'custom_widenet' using dot notation.
custom_widenet.parameters


<bound method Module.parameters of Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)>

In [6]:
# Display the parameters and their names in 'custom_deepnet'.
for p in custom_deepnet.named_parameters():
    print(p)
    print(' ')


('0.weight', Parameter containing:
tensor([[-0.5748,  0.4295],
        [ 0.6103,  0.2118]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([0.4601, 0.4546], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.3398, -0.1026],
        [ 0.6497,  0.6662]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([0.0060, 0.2367], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.2813,  0.0407],
        [-0.5980,  0.5548],
        [ 0.1765, -0.2279]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.5412,  0.4313,  0.0912], requires_grad=True))
 


In [7]:
# Count the number of bias nodes in both 'custom_widenet' and 'custom_deepnet'.
numNodesInWide = 0
for p in custom_widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName, paramVect in custom_deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print('There are %s nodes in the wide network.' % numNodesInWide)
print('There are %s nodes in the deep network.' % numNodesInDeep)


There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# Display the parameters (weights and biases) in 'custom_widenet'.
for p in custom_widenet.parameters():
    print(p)
    print(' ')


Parameter containing:
tensor([[ 0.1153,  0.2552],
        [-0.4763, -0.3817],
        [ 0.0397,  0.3875],
        [-0.4508,  0.5940]], requires_grad=True)
 
Parameter containing:
tensor([-0.2770,  0.2577, -0.0303, -0.5783], requires_grad=True)
 
Parameter containing:
tensor([[ 0.4215,  0.1189, -0.0617,  0.4416],
        [-0.2441,  0.4047,  0.1732, -0.3367],
        [-0.2702, -0.1068,  0.2345, -0.3709]], requires_grad=True)
 
Parameter containing:
tensor([-0.3230, -0.4662, -0.0693], requires_grad=True)
 


In [8]:
# Count the total number of trainable parameters in 'custom_widenet'.
nparams = 0
for p in custom_widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' % p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters' % nparams)


This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [8]:
# Calculate the total number of trainable parameters in 'custom_widenet' using list comprehension.
nparams = np.sum([p.numel() for p in custom_widenet.parameters() if p.requires_grad])
print('Widenet has %s parameters' % nparams)

# Calculate the total number of trainable parameters in 'custom_deepnet' using list comprehension.
nparams = np.sum([p.numel() for p in custom_deepnet.parameters() if p.requires_grad])
print('Deepnet has %s parameters' % nparams)


Widenet has 27 parameters
Deepnet has 21 parameters


In [10]:
!pip install torchsummary


In [11]:
# Import 'torchsummary' and summarize the 'custom_widenet' model with input shape (1, 2).
from torchsummary import summary
summary(custom_widenet, (1, 2))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
