# Matrix Multiplication and Its Applications in Deep Learning

Matrix multiplication, also known as matrix product, plays a fundamental role in many mathematical and computational applications, especially in the field of deep learning and neural networks. In deep learning, matrices and matrix multiplication are used extensively for tasks such as linear transformations, feature extraction, and neural network training. Let's explore matrix multiplication and its applications.

## Matrix Multiplication Overview

Matrix multiplication is an operation that takes two matrices and produces a third matrix, known as the result or product matrix. It's defined as follows:

Given two matrices:
- Matrix A with dimensions (m x n)
- Matrix B with dimensions (n x p)

The result matrix C has dimensions (m x p), and its elements are computed as follows:




## Applications in Deep Learning

Matrix multiplication is crucial in deep learning for the following reasons:

1. **Linear Transformations**: In neural networks, weights and biases are represented as matrices. Matrix multiplication is used to apply linear transformations to input data, which allows neural networks to learn complex relationships between features.

2. **Layer Operations**: Each layer in a neural network performs matrix multiplication with its inputs. This process, combined with activation functions, forms the core of neural network operations.

3. **Convolutional Layers**: In convolutional neural networks (CNNs), convolution operations are implemented as a form of matrix multiplication with convolutional kernels.

4. **Matrix Factorization**: Techniques like singular value decomposition (SVD) and matrix factorization are used in recommendation systems and dimensionality reduction.

5. **Backpropagation**: During training, gradient descent algorithms require computing gradients using matrix operations, making matrix multiplication a vital component of optimization.

## Examples of Matrix Multiplication in Python (NumPy)

Let's explore some examples of matrix multiplication in Python using the NumPy library:



```python


In [3]:
from IPython.display import display, Math
import numpy as np

# Input two vectors as lists
vector_a = input("Enter the first vector (comma-separated values): ").split(',')
vector_b = input("Enter the second vector (comma-separated values): ").split(',')

# Convert input values to NumPy arrays
vector_a = np.array([float(val.strip()) for val in vector_a])
vector_b = np.array([float(val.strip()) for val in vector_b])

# Calculate the dot product step by step
step_by_step = []
dot_product = 0
for i in range(len(vector_a)):
    step_by_step.append(f"{vector_a[i]} \\cdot {vector_b[i]}")
    dot_product += vector_a[i] * vector_b[i]

# Display the vectors and their multiplication as equations using LaTeX
equation_a = r'$$\mathbf{A} = [' + ', '.join(map(str, vector_a)) + ']$$'
equation_b = r'$$\mathbf{B} = [' + ', '.join(map(str, vector_b)) + ']$$'
equation_step_by_step = r'$$\mathbf{A} \cdot \mathbf{B} = ' + ' + '.join(step_by_step) + r' = ' + str(dot_product) + r'$$'

display(Math(equation_a))
display(Math(equation_b))
display(Math(equation_step_by_step))


Enter the first vector (comma-separated values): 3,4,5
Enter the second vector (comma-separated values): 2,3


IndexError: index 2 is out of bounds for axis 0 with size 2

### Example 1: Basic Matrix Multiplication

In [5]:
import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result1 = np.dot(A, B)
result1

array([[19, 22],
       [43, 50]])

In [6]:
import numpy as np

# Create a matrix and a scalar
matrix = np.array([[1, 2], [3, 4]])
scalar = 2

# Perform matrix-scalar multiplication (broadcasting)
result2 = matrix * scalar
result2

array([[2, 4],
       [6, 8]])

In [10]:
import numpy as np

# Create batched matrices
batched_matrix1 = np.random.rand(3, 2, 2)  # Batch size: 3, Each matrix: 2x2
batched_matrix2 = np.random.rand(3, 2, 2)

# Perform batched matrix multiplication
result3 = np.matmul(batched_matrix1, batched_matrix2)


In [12]:
result3.shape

(3, 2, 2)

In [9]:
batched_matrix1.shape

(3, 2, 2)

In [ ]:
import numpy as np

# Create a matrix and a vector
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([2, 3])

# Perform matrix-vector multiplication
result4 = np.matmul(matrix, vector)


In [13]:
import numpy as np
from scipy.sparse import coo_matrix

# Create two sparse matrices
sparse_matrix1 = coo_matrix(([1, 2], ([0, 2], [1, 0])), shape=(3, 3))
sparse_matrix2 = coo_matrix(([3, 4], ([0, 2], [1, 0])), shape=(3, 3))

# Perform sparse matrix multiplication
result5 = sparse_matrix1.dot(sparse_matrix2)


In [17]:
type(sparse_matrix1.todense())

numpy.matrix

In [ ]:
import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication with @ operator
result6 = A @ B


In [ ]:
import numpy as np

# Create two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])  # Dimensions: 2x3
B = np.array([[7, 8], [9, 10], [11, 12]])  # Dimensions: 3x2

# Perform matrix multiplication
result7 = np.dot(A, B)


In [ ]:
import numpy as np

# Create batched matrices
batched_matrix1 = np.random.rand(3, 2, 2)  # Batch size: 3, Each matrix: 2x2
batched_matrix2 = np.random.rand(3, 2, 2)

# Perform batched matrix multiplication with @ operator
result8 = batched_matrix1 @ batched_matrix2


In [2]:
import numpy as np

# Create a matrix and a vector
matrix = np.array([[1, 2], [3, 4]])  # Dimensions: 2x2
vector = np.array([2, 3])  # Dimensions: 2

# Perform matrix-vector multiplication with @ operator
result9 = matrix @ vector


array([ 8, 18])

In [ ]:
import torch

# Create two matrices
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

# Perform matrix multiplication
result1 = torch.matmul(A, B)


In [ ]:
import torch

# Create two matrices
A = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Dimensions: 2x3
B = torch.tensor([[7, 8], [9, 10], [11, 12]])  # Dimensions: 3x2

# Perform matrix multiplication
result2 = torch.matmul(A, B)


In [ ]:
import torch

# Create batched matrices
batched_matrix1 = torch.randn(3, 2, 2)  # Batch size: 3, Each matrix: 2x2
batched_matrix2 = torch.randn(3, 2, 2)

# Perform batched matrix multiplication
result3 = torch.matmul(batched_matrix1, batched_matrix2)


In [18]:
import torch

# Create a matrix and a vector
matrix = torch.tensor([[1, 2], [3, 4]])  # Dimensions: 2x2
vector = torch.tensor([2, 3])  # Dimensions: 2

# Perform matrix-vector multiplication
result4 = torch.matmul(matrix, vector)


In [19]:
result4

tensor([ 8, 18])

In [ ]:
import torch

# Create a matrix and a scalar
matrix = torch.tensor([[1, 2], [3, 4]])  # Dimensions: 2x2
scalar = 2

# Perform matrix-scalar multiplication (broadcasting)
result5 = torch.matmul(matrix, scalar)


In [21]:
import torch

# Create high-dimensional tensors
A = torch.randn(2, 3, 4, 5)  # Dimensions: 2x3x4x5
B = torch.randn(2, 5, 4, 3)  # Dimensions: 2x5x4x3

# Perform high-dimensional matrix multiplication
# result6 = torch.matmul(A, B)


In [31]:
A

tensor([[[[ 1.3385, -0.0165, -1.3635, -0.0923, -1.4550],
          [ 0.6669,  0.0727,  1.7798, -0.0961,  1.1318],
          [ 0.4495, -1.1967, -0.1342, -0.0177, -1.5273],
          [-0.0337, -0.0809, -1.6889, -1.6471, -1.3760]],

         [[ 0.2396, -0.2928,  1.2080,  1.9246, -0.3690],
          [ 1.1440, -1.1569,  0.3526,  0.9215, -1.6693],
          [-0.7641,  0.4813,  1.1039,  0.8717, -0.5538],
          [-0.0970, -0.3829,  0.7943,  0.6465, -0.6360]],

         [[-0.6867,  1.1335,  1.0186,  0.0498,  0.8098],
          [-0.0796, -0.5695, -0.9594, -0.5342, -0.3943],
          [-1.4320,  0.3233, -0.9237, -1.2492,  0.8806],
          [ 0.2203,  1.9052,  0.6359, -0.4368,  0.0044]]],


        [[[-0.3239, -0.7547,  0.5845, -0.4220, -1.2488],
          [ 0.8115,  0.7543,  1.9461,  0.3727,  0.9628],
          [ 0.7900, -0.2339,  0.0687,  0.8278, -1.0773],
          [ 0.8491, -1.6239, -0.4301, -0.7720,  0.5583]],

         [[-0.8237, -1.0298,  0.2170,  1.4983, -1.1180],
          [ 1.3119,  

In [26]:
B[1][1][1]

tensor([-0.2572, -0.4800, -0.3163])

In [ ]:
import torch

# Create complex tensors
real_A = torch.randn(2, 2)
imag_A = torch.randn(2, 2)
real_B = torch.randn(2, 2)
imag_B = torch.randn(2, 2)

# Combine real and imaginary parts to form complex tensors
A = torch.complex(real_A, imag_A)
B = torch.complex(real_B, imag_B)

# Perform complex matrix multiplication
result7 = torch.matmul(A, B)
