# Matrix Transpose with NumPy and PyTorch

Matrix transpose is a fundamental operation in linear algebra, involving swapping the rows and columns of a matrix. In Python, you can perform matrix transpose easily using libraries like NumPy and PyTorch.

## NumPy

NumPy is a powerful library for numerical computing in Python. You can use it to create and manipulate arrays, including transposing matrices.

### Transposing a Matrix with NumPy

To transpose a matrix with NumPy, you can use the `numpy.transpose()` function or simply `.T` attribute.

Useful Applications:
- Transposing matrices is crucial for operations like matrix multiplication, where the dimensions of matrices need to align correctly.
- It's used in data manipulation and feature engineering in data science and machine learning.

References:
- [NumPy Documentation: NumPy Transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

## PyTorch

PyTorch is another popular library, particularly for deep learning. It offers tensor operations similar to NumPy.

### Transposing a Matrix with PyTorch

To transpose a matrix with PyTorch, you can use the `.t()` method or the `torch.transpose()` function.

Useful Applications:
- PyTorch is widely used in deep learning, and matrix transpose is essential for neural network operations like weight initialization and gradient computations.

References:
- [PyTorch Documentation: PyTorch Transpose](https://pytorch.org/docs/stable/generated/torch.transpose.html)


In [14]:
import numpy as np

# Example 1: Transposing a 2x3 matrix
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Using np.transpose() function
transpose_matrix1 = np.transpose(matrix1)

# Display the original and transposed matrices
print("Original Matrix:")
print(matrix1)

print("\nTransposed Matrix:")
print(transpose_matrix1)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [15]:
matrix1.shape

(2, 3)

In [16]:
import numpy as np

# Example 2: Transposing a 3x2 matrix
matrix2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

# Using the .T attribute
transpose_matrix2 = matrix2.T

# Display the original and transposed matrices
print("Original Matrix:")
print(matrix2)

print("\nTransposed Matrix:")
print(transpose_matrix2)


Original Matrix:
[[ 7  8]
 [ 9 10]
 [11 12]]

Transposed Matrix:
[[ 7  9 11]
 [ 8 10 12]]


In [17]:
matrix2.shape

(3, 2)

In [18]:
import numpy as np

# Example 3: Transposing a random 3x4 matrix
matrix3 = np.random.randint(1, 10, (3, 4))

# Using np.transpose() function
transpose_matrix3 = np.transpose(matrix3)

# Display the original and transposed matrices
print("Original Matrix:")
print(matrix3)

print("\nTransposed Matrix:")
print(transpose_matrix3)


Original Matrix:
[[1 9 1 5]
 [4 4 9 9]
 [2 7 1 5]]

Transposed Matrix:
[[1 4 2]
 [9 4 7]
 [1 9 1]
 [5 9 5]]


In [19]:
transpose_matrix3.shape

(4, 3)

In [20]:
import numpy as np

# Example 4: Transposing a 1x3 matrix
matrix4 = np.array([[1, 2, 3]])

# Using the .T attribute
transpose_matrix4 = matrix4.T

# Display the original and transposed matrices
print("Original Matrix:")
print(matrix4)

print("\nTransposed Matrix:")
print(transpose_matrix4)


Original Matrix:
[[1 2 3]]

Transposed Matrix:
[[1]
 [2]
 [3]]


In [21]:
import numpy as np

# Example 5: Transposing a 3x1 matrix
matrix5 = np.array([[4],
                   [5],
                   [6]])

# Using the .T attribute
transpose_matrix5 = matrix5.T

# Display the original and transposed matrices
print("Original Matrix:")
print(matrix5)

print("\nTransposed Matrix:")
print(transpose_matrix5)


Original Matrix:
[[4]
 [5]
 [6]]

Transposed Matrix:
[[4 5 6]]


In [22]:
import torch

# Example 1: Transposing a 2x3 tensor
tensor1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Using the .t() method
transpose_tensor1 = tensor1.t()

# Display the original and transposed tensors
print("Original Tensor:")
print(tensor1)

print("\nTransposed Tensor:")
print(transpose_tensor1)


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transposed Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [23]:
import torch

# Example 2: Transposing a 3x2 tensor
tensor2 = torch.tensor([[7, 8],
                       [9, 10],
                       [11, 12]])

# Using the torch.transpose() function
transpose_tensor2 = torch.transpose(tensor2, 0, 1)

# Display the original and transposed tensors
print("Original Tensor:")
print(tensor2)

print("\nTransposed Tensor:")
print(transpose_tensor2)


Original Tensor:
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

Transposed Tensor:
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [24]:
import torch

# Example 3: Transposing a random 3x4 tensor
tensor3 = torch.randn(3, 4)

# Using the .t() method
transpose_tensor3 = tensor3.t()

# Display the original and transposed tensors
print("Original Tensor:")
print(tensor3)

print("\nTransposed Tensor:")
print(transpose_tensor3)


Original Tensor:
tensor([[-0.4704, -1.2543,  0.0933,  1.1601],
        [-0.1188,  0.6931, -0.3624, -0.6102],
        [-2.0533, -0.4116,  0.0890,  0.5117]])

Transposed Tensor:
tensor([[-0.4704, -0.1188, -2.0533],
        [-1.2543,  0.6931, -0.4116],
        [ 0.0933, -0.3624,  0.0890],
        [ 1.1601, -0.6102,  0.5117]])


In [25]:
import torch

# Example 4: Transposing a 1x3 tensor
tensor4 = torch.tensor([[1, 2, 3]])

# Using the .t() method
transpose_tensor4 = tensor4.t()

# Display the original and transposed tensors
print("Original Tensor:")
print(tensor4)

print("\nTransposed Tensor:")
print(transpose_tensor4)


Original Tensor:
tensor([[1, 2, 3]])

Transposed Tensor:
tensor([[1],
        [2],
        [3]])


In [26]:
import torch

# Example 5: Transposing a 3x1 tensor
tensor5 = torch.tensor([[4],
                       [5],
                       [6]])

# Using the .t() method
transpose_tensor5 = tensor5.t()

# Display the original and transposed tensors
print("Original Tensor:")
print(tensor5)

print("\nTransposed Tensor:")
print(transpose_tensor5)


Original Tensor:
tensor([[4],
        [5],
        [6]])

Transposed Tensor:
tensor([[4, 5, 6]])
